### ISSUE TITLE
Replace assembly.xml with maven-jar-plugin

### ISSUE THREAD

**Issue by mjsax** [mjsax/aeolus#12]

**Comment by krichter722** [comment]
`find . -name assembly.xml` returns no results. What are you referring to?

**Comment by mjsax** [comment]
It's an open issue in uncommited code in my local repository. Just I reminder to myself.

**Comment by krichter722** [comment]
FYI, I'm randomly experiencing `Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4.1:single (make-assembly) on project optimization: Failed to create assembly: Error adding file to archive: /mnt/DATA/richter/Dateien/stratosphere/aeolus/optimization/target/classes/de/hub/cs/dbis/aeolus/scheduler/Scheduler.class isn't a file.` during `mvn install`. Might be related.

**Comment by krichter722** [comment]
This is a blocker now. I can no longer build `optimization` with 80c8129feb9eb3e6c9c2b27b0ec5acba299a58d1. The failing file `optimization/target/classes/de/hub/cs/dbis/aeolus/scheduler/Scheduler.class` doesn't exist after failure of `mvn clean install`.

**Comment by mjsax** [comment]
This assembly should have never been commited... My bad. I just removed it, and pushed it to the master.

But your last commits, broke the master!!! 
[ERROR] /home/mjsax/workspace_aeolus/aeolus/queries/lrb/src/main/java/storm/lrb/bolt/AccidentNotificationBolt.java:[143,55] cannot find symbol
  symbol:   method getAccNotification(storm.lrb.model.PosReport)
  location: variable accident of type storm.lrb.model.AccidentImmutable

You need to fix this asap!
